### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by Justman10000** [box/mojito#938] opened 2023-04-26 13:05 UTC

**Comment by Justman10000** [comment] 2023-04-26 13:05
@aurambaj

**Comment by aurambaj** [comment] 2023-07-18 21:43
closing since there is not enough information to reproduce

**Closed by aurambaj** 2023-07-18 21:43 UTC

**Comment by Justman10000** [comment] 2023-07-19 01:58
@aurambaj

Really? I write three fucking months ago and all you do is close issues? Instead of waiting for an answer like any normal person? If you keep this up, I won't be the only one who fucks off here
